Exception on /login [POST]
Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\asus\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\asus\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\asus\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\asus\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\asus\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Imagine Cup\Eatfit-Backend\app\routes.py", line 22, in login
    return postgres_ob
NameError: name 'postgres_ob' is not defined
